### ISSUE TITLE
demo seems broken?

### ISSUE THREAD

**Issue by simeydotme** [yairEO/knobs#10]
When i viewed the CodePen demo, there's no "knobs" button visible... just a pointing finger 

https://user-images.githubusercontent.com/2817396/171353951-2d97cbc6-b720-45cb-ae2e-ddf8f0655032.mov

**Comment by yairEO** [comment]
Are you in incognito mode? Your browser is blocking access to the `localStorage` 

I've checked the demo and it's fine, just in incognito mode it won't work

**Comment by simeydotme** [comment]
just using firefox regular :) 
but yes, I see it working now!
