### ISSUE TITLE
Theme -> Background property

### ISSUE THREAD

**Issue by torrobinson** [yairEO/knobs#11]
Hello,

I'm trying to adjust the background of the knobs panel to be transparent but am running into an issue:

1) Your readme calls the background property 'backgroud' which I believe is a spelling error
2) Changing the background/backgroud doesn't appear to make a difference and is always black:
![image](https://user-images.githubusercontent.com/4401999/200050197-51ee786d-dfed-49c7-aba8-7d79d776dbd3.png)

Can you please provide me an example of how to change the background color to something that's not black using the Knobs config?

Thanks!

**Comment by yairEO** [comment]
Just now [released version `1.3.5`](https://github.com/yairEO/knobs/releases/tag/v1.3.5) which solves this, but the real `theme` property for manipulating the background should be `base-color` and not `background` (I've also changed that in the README)

**Comment by torrobinson** [comment]
Beautiful, works now, thanks!
