### ISSUE TITLE
Color picker does not function on Brave.

### ISSUE THREAD

**Issue by miyucomics** [yairEO/knobs#3]
I know it only works on modern browsers, but Brave is essentially Chrome. I am not sure what to send so you can request it by commenting.

**Comment by miyucomics** [comment]
Update: upon closer inspection, it actually works once before never working again until I refresh.

**Comment by yairEO** [comment]
so open Brave a ticket, it's obviously an issue specifically to their product... maybe they are using some older version of the Chromium/Blink engine. 

What is your use-case for Knobs?

**Comment by miyucomics** [comment]
I am trying to change a JavaScript variable. Does it happen because the colour picker appears on top of the Knobs menu and Knobs is on the top right of the screen?

**Comment by yairEO** [comment]
no, not related
