### ISSUE TITLE
Feature request: Optional numeric input when using the "range" type

### ISSUE THREAD

**Issue by mvasigh** [yairEO/knobs#5]
The `range` knob type is great! However, sometimes I need to have both the slider input for rough modulation as well as a numeric input next to it representing the value, for precision. It would be great to have a way to directly provide the value to the range input as well, and have it be an optional setting.

I'm happy to PR this! It'll probably be a couple of weeks before I can work on it though, but didn't want to lose the idea.

**Comment by yairEO** [comment]
For precision you should use the mouse wheel (over the slider component) instead of holding & dragging.

No need for a PR as this can be done already:

https://jsbin.com/zecajoj/1/edit?html,css,js,output
