### ISSUE TITLE
Uncaught TypeError: Knobs is not a constructor

### ISSUE THREAD

**Issue by Tiibiix** [yairEO/knobs#6]
Since todays Update:

`Uncaught TypeError: Knobs is not a constructor`

**Comment by yairEO** [comment]
Hi yeah I've pushed an urgent fix for that. I worked hard for a week to release a new version with tons of fixes and improvements and I did a mistake that I've discovered right after pushing the release, so I've released a patch just few minutes afterwards. Please use version `v1.3.2` at the least

**Comment by Tiibiix** [comment]
Heya, thanks for the quick response.
Love Knobs btw 😃

**Comment by yairEO** [comment]
I love Knobs also! what are you using it for?

**Comment by Tiibiix** [comment]
I create animations in the canvas mostly and i love giving the people options to adjust the animation to their liking.
Most of them are based off simple mathematical equations so putting some of those variables into knobs can do wonders.
I acctually used dat.gui before but knobs is way more user-friendy and absolutely love the UI/UX.

Here is my latest Pen using Knobs if you want to check it out: https://codepen.io/Tibixx/pen/OJgNWdv

(I hope you dont mind i took the Pointing emoji from your example, figured its a nice way to make it stand out, since it was barely visible on my dark background)

Cheers

**Comment by yairEO** [comment]
WOW it's beautiful! you are super talented!

**Comment by Tiibiix** [comment]
Thanks, really appreciate it :)

Stay safe!
