### ISSUE TITLE
Probably a bug

### ISSUE THREAD

**Issue by ziadkh0** [yairEO/knobs#7]
On the [Tagify page](https://yaireo.github.io/tagify/), in the "knobs" panel, when hovering of the `tag-remove-bg-btn--hover` the whole panel changes width instead of the color rectangle next to it.

Browser: Firefox Developer Edition v93.0b9 (64-bit)
OS: Arch linux

**Comment by yairEO** [comment]
Nice catch! :) Thanks a lot for letting me know
